[package]
name = "composition_storage_merge_pure_mixin_contract"
type = "contract"
authors = ["Wonderland"]
compiler_version = ">=1.0.0"

[dependencies]
aztec = { path = "../../aztec" }
composition_fixtures = { path = "../fixtures" }
